C_OBJS=sqlite_server.o sqlite3.o
ASM_OBJS=
COMPONENT=sqlite.o
INTERFACES=torrent
DEPENDENCIES=printc cbufp cbuf_c evt lock mem_mgr_large valloc sched
IF_LIB=$(SQLITE3_LIB)

include ../Makefile.subsubdir
