C_OBJS=test_sqlite3.o
ASM_OBJS=
COMPONENT=unit_sqlite3.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock
IF_LIB=$(SQLITE3_LIB)

include ../../Makefile.subsubdir