C_OBJS=unit_sqlite_server.o
ASM_OBJS=
COMPONENT=test_sqlite_server.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock
IF_LIB=

include ../../Makefile.subsubdir

